import cx_Freeze
import os

os.environ['TCL_LIBRARY'] = "C:\\Program Files\\Python\\tcl\\tcl8.6"
os.environ['TK_LIBRARY'] = "C:\\Program Files\\Python\\tcl\\tk8.6"
executables = [cx_Freeze.Executable("game.py")]

cx_Freeze.setup(
    name="The Color That Fell From the Sky",
    options={"build_exe": {"packages":["pygame"],
                           "include_files":["Heavitas.ttf",
                                            'Roboto-Light.ttf',
                                            'high scores.csv',
                                            ('music/crown.wav', 'music/crown.wav'),
                                            ('music/game over.wav', 'music/game over.wav'),
                                            ('music/george_explosion.wav', 'music/george_explosion.wav'),
                                            ('music/john_explosion.wav', 'music/john_explosion.wav'),
                                            ('music/main theme.wav', 'music/main theme.wav'),
                                            ('music/paul_explosion.wav', 'music/paul_explosion.wav'),
                                            ('music/planet recovery.wav', 'music/planet recovery.wav'),
                                            ('music/planet_explosion.wav', 'music/planet_explosion.wav'),
                                            ('music/player_explosion.wav', 'music/player_explosion.wav'),
                                            ('music/ringo_explosion.wav', 'music/ringo_explosion.wav'),
                                            ('music/shield.wav', 'music/shield.wav'),
                                            ('music/shot.wav', 'music/shot.wav'),
                                            ('music/start screen.wav', 'music/start screen.wav'),
                                            ('music/tea.wav', 'music/tea.wav'),
                                            ('sprites/bubble_1.png', 'sprites/bubble_1.png'),
                                            ('sprites/bubble_2.png', 'sprites/bubble_2.png'),
                                            ('sprites/bubble_3.png', 'sprites/bubble_3.png'),
                                            ('sprites/bubble_4.png', 'sprites/bubble_4.png'),
                                            ('sprites/bubble_5.png', 'sprites/bubble_5.png'),
                                            ('sprites/bullet.png', 'sprites/bullet.png'),
                                            ('sprites/controls_screen.png', 'sprites/controls_screen.png'),
                                            ('sprites/credits_screen.png', 'sprites/credits_screen.png'),
                                            ('sprites/crown.png', 'sprites/crown.png'),
                                            ('sprites/debris_blue.png', 'sprites/debris_blue.png'),
                                            ('sprites/debris_green.png', 'sprites/debris_green.png'),
                                            ('sprites/debris_orange.png', 'sprites/debris_orange.png'),
                                            ('sprites/debris_yellow.png', 'sprites/debris_yellow.png'),
                                            ('sprites/george.png', 'sprites/george.png'),
                                            ('sprites/go_01.png', 'sprites/go_01.png'),
                                            ('sprites/go_02.png', 'sprites/go_02.png'),
                                            ('sprites/go_03.png', 'sprites/go_03.png'),
                                            ('sprites/john.png', 'sprites/john.png'),
                                            ('sprites/p_1_000.png', 'sprites/p_1_000.png'),
                                            ('sprites/p_1_135.png', 'sprites/p_1_135.png'),
                                            ('sprites/p_1_180.png', 'sprites/p_1_180.png'),
                                            ('sprites/p_1_225.png', 'sprites/p_1_225.png'),
                                            ('sprites/p_1_270.png', 'sprites/p_1_270.png'),
                                            ('sprites/p_1_315.png', 'sprites/p_1_315.png'),
                                            ('sprites/p_2_000.png', 'sprites/p_2_000.png'),
                                            ('sprites/p_2_045.png', 'sprites/p_2_045.png'),
                                            ('sprites/p_2_090.png', 'sprites/p_2_090.png'),
                                            ('sprites/p_2_135.png', 'sprites/p_2_135.png'),
                                            ('sprites/p_2_180.png', 'sprites/p_2_180.png'),
                                            ('sprites/p_2_225.png', 'sprites/p_2_225.png'),
                                            ('sprites/p_2_270.png', 'sprites/p_2_270.png'),
                                            ('sprites/p_2_315.png', 'sprites/p_2_315.png'),
                                            ('sprites/p_3_000.png', 'sprites/p_3_000.png'),
                                            ('sprites/p_3_045.png', 'sprites/p_3_045.png'),
                                            ('sprites/p_3_090.png', 'sprites/p_3_090.png'),
                                            ('sprites/p_3_135.png', 'sprites/p_3_135.png'),
                                            ('sprites/p_3_180.png', 'sprites/p_3_180.png'),
                                            ('sprites/p_3_225.png', 'sprites/p_3_225.png'),
                                            ('sprites/p_3_270.png', 'sprites/p_3_270.png'),
                                            ('sprites/p_3_315.png', 'sprites/p_3_315.png'),
                                            ('sprites/p_4_000.png', 'sprites/p_4_000.png'),
                                            ('sprites/p_4_045.png', 'sprites/p_4_045.png'),
                                            ('sprites/p_4_090.png', 'sprites/p_4_090.png'),
                                            ('sprites/p_4_135.png', 'sprites/p_4_135.png'),
                                            ('sprites/p_4_180.png', 'sprites/p_4_180.png'),
                                            ('sprites/p_4_225.png', 'sprites/p_4_225.png'),
                                            ('sprites/p_4_270.png', 'sprites/p_4_270.png'),
                                            ('sprites/p_4_315.png', 'sprites/p_4_315.png'),
                                            ('sprites/p_5_000.png', 'sprites/p_5_000.png'),
                                            ('sprites/p_5_045.png', 'sprites/p_5_045.png'),
                                            ('sprites/p_5_090.png', 'sprites/p_5_090.png'),
                                            ('sprites/p_5_135.png', 'sprites/p_5_135.png'),
                                            ('sprites/p_5_180.png', 'sprites/p_5_180.png'),
                                            ('sprites/p_5_225.png', 'sprites/p_5_225.png'),
                                            ('sprites/p_5_270.png', 'sprites/p_5_270.png'),
                                            ('sprites/p_5_315.png', 'sprites/p_5_315.png'),
                                            ('sprites/paul.png', 'sprites/paul.png'),
                                            ('sprites/pause_screen.png', 'sprites/pause_screen.png'),
                                            ('sprites/planet_01.png', 'sprites/planet_01.png'),
                                            ('sprites/planet_02.png', 'sprites/planet_02.png'),
                                            ('sprites/planet_03.png', 'sprites/planet_03.png'),
                                            ('sprites/planet_04.png', 'sprites/planet_04.png'),
                                            ('sprites/planet_05.png', 'sprites/planet_05.png'),
                                            ('sprites/planet_06.png', 'sprites/planet_06.png'),
                                            ('sprites/ringo.png', 'sprites/ringo.png'),
                                            ('sprites/shield 1.png', 'sprites/shield 1.png'),
                                            ('sprites/shield 2.png', 'sprites/shield 2.png'),
                                            ('sprites/shield 3.png', 'sprites/shield 3.png'),
                                            ('sprites/shield 4.png', 'sprites/shield 4.png'),
                                            ('sprites/shield 5.png', 'sprites/shield 5.png'),
                                            ('sprites/shield 6.png', 'sprites/shield 6.png'),
                                            ('sprites/shield 7.png', 'sprites/shield 7.png'),
                                            ('sprites/star_05.png', 'sprites/star_05.png'),
                                            ('sprites/star_10.png', 'sprites/star_10.png'),
                                            ('sprites/story 1.png', 'sprites/story 1.png'),
                                            ('sprites/story 2.png', 'sprites/story 2.png'),
                                            ('sprites/story 3.png', 'sprites/story 3.png'),
                                            ('sprites/story 4.png', 'sprites/story 4.png'),
                                            ('sprites/story 5.png', 'sprites/story 5.png'),
                                            ('sprites/tardis.png', 'sprites/tardis.png'),
                                            ('sprites/tea.png', 'sprites/tea.png'),
                                            ('sprites/title_screen.png', 'sprites/title_screen.png'),
                                            ('sprites/umbrella.png', 'sprites/umbrella.png')]}},
    executables=executables

    )
